config/routes.rb
NewModified::Application.routes.draw do
	root to: 'static_pages#home'

	match '/help', to: 'static_pages#help'

	match '/about', to: 'static_pages#about'

	match '/unauthorized', to: 'static_pages#unauthorized'

	match '/contact', to: 'static_pages#contact'

	match '/admin', to: 'static_pages#admin'

	match '/chat', to: 'static_pages#chat'

	match '/search', to: 'search#search_all'

	resources :users

	match '/user_videos', to: 'users#user_videos'
	match '/user_posts', to: 'users#user_posts'
	match '/user_articles', to: 'users#user_articles'
	match '/user_data', to: 'users#export'
	match '/who_online', to: 'users#who_online'
	match '/enable_chat', to: 'users#user_enable_chat'
	match '/timeline/:id', to: 'users#timeline'
	match '/sessions/:id', to: 'users#sessions_timeline'

	match '/signup', to: 'users#new'

	match '/clear_notifications', to: 'users#clear_notifications'

	match '/reset/:reset_code', to:'users#reset_password'

	match '/sorted_users', to:'users#sorted_index'

	resources :sessions, only: [:new, :create, :destroy]

	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete
	match '/signout', to: 'sessions#destroy'
	match '/forgotpassword', to: 'sessions#forgot_password'
	match '/resetpassword', to: 'sessions#reset_password'

	resources :feeds, only: [:index, :create, :update, :edit]

	match 'feeds/:permalink', controller: 'feeds', action: 'show', as: "feed"

	resources :achievements

	match 'new_achievement', controller: 'achievements', action: 'create'
	match 'update_achievement', controller: 'achievements', action: 'update'

	resources :training_sessions
	match 'new_training_session', controller: 'training_sessions', action: 'create'
	match 'update_training_session', controller: 'training_sessions', action: 'update'

	match 'training_drills/select', to: 'training_drills#select'
	match 'training_drills/init', to: 'training_drills#init'

	resources :training_drills

	resources :training_drill_results

	resources :posts

	resources :articles

	resources :videos do
		get 'search', on: :collection
		post 'touch'
	end

	match '/feedbacks', to: 'videos#feedback_index'

	match '/saveVideo', to: 'videos#import', via: :post

	resources :blog_posts

	resources :blogs

	match '/importblog', to:"blogs#import"
	match '/performimport', to:"blogs#perform_import"
	match '/perform_blogpost_import', to:"blogs#perform_blogpost_import"
	match '/initblog', to: "blogs#init_blog"
	match '/blogs/rename', to: "blogs#rename", via: :post

	resources :comments

	resources :messages, only: [:new, :create, :index, :show]

	match '/getmail', to: 'messages#get_latest'
	match '/markread', to: 'messages#mark_as_read'

	resources :conversations, only: [:show]

	resources :likes, only: [:new, :create, :destroy]

	match '/like', to: 'likes#create', via: :post
	match '/unlike', to: 'likes#destroy', via: :delete

	resources :notifications, only: [:index]
	match '/activities', to: 'notifications#index'
	match '/getnotifications', to: 'notifications#get_latest'

	resources :events
	resources :competitions, only: [:show, :update]

	match 'competition/reorder/:id', to: 'competitions#reorder', via: :put, as: "reorder"

	resources :results

	match 'static/:name', controller: 'pages', action: 'show', as: "page"

	match 'static/edit/:name', controller: 'pages', action: 'edit', as: "edit_page"

	match 'static/update/:name', controller: 'pages', action: 'update', via: :put

	resources :categories

	resources :video_categories

	resources :video_super_categories

	match 'video_tutorials/:permalink', controller: 'video_super_categories', action: 'show', as: "video_super_category"

	match '/stop_listening/:guid', to: 'listeners#remove_listener'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include ApplicationHelper
  require 'will_paginate/array'
  before_filter :check_for_mobile

  def chat
    render layout: false
  end

  def home
    @first_timer = first_time_visitor?
    if mobile_device? || signed_in? || request.xhr?
      @feed_front_page = true
      per_page = params[:items_count] || 5
      @feed = Feed.find_by_store_name("main feed")
      @feed = seed_main_feed if @feed.nil?
      @feed_items = @feed.feed_items([BlogPost, Achievement]) do |collection|
        privacy_query(collection)
      end
      @feed_items = @feed_items.paginate(page: params[:page], :per_page=> per_page)
      if mobile_device?
        @feeds = Feed.where("hidden = ?", false)
      end
      # Christmas calendar code
      unless params[:dt].nil?
        today = params[:dt].to_i
      else
        today = Date.today.to_s
        today = today.gsub!('-','').to_i
      end
      if (today>=20131201 && today<=20131220)
        daysInCalendar = today - 20131201
        base_id = 573
        @video_of_day = Video.find(base_id+daysInCalendar)
      end
      # End of christmas calendar code
      if request.xhr?
        render partial: 'shared/feed_item', collection: @feed_items, comments_shown: false
      end
    else
      @full_site_layout = true
      @feed_front_page = false
      @article = Article.find_by_permalink("front-page")
    end
  end

  def admin
    @feed = Feed.find_by_store_name("admin feed")
    @feed = seed_admin_feed if @feed.nil?
    @feed_items = @feed.feed_items.paginate(page: params[:page], per_page: 10)
    @virtual_profiles = User.where(registered: false)
    if request.xhr?
      render partial: 'shared/feed_item', collection: @feed_items, comments_shown: false
    end
  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def my_tinymce()
		get_tinymce_code.html_safe
	end

	def get_tinymce_code
		<<-eos
		   <script>
			tinyMCE.init({
				"mode":"specific_textareas",
				"editor_selector":"tinymce",
				"theme":"advanced",
				skin : "bootstrap",
				"theme_advanced_toolbar_location":"top","theme_advanced_toolbar_align":"left","theme_advanced_statusbar_location":"bottom","theme_advanced_resizing":true,
				"theme_advanced_buttons1_add":"fontselect,fontsizeselect,pdw_toggle",
				"theme_advanced_buttons2_add":"forecolor,backcolor,emotions",
				"theme_advanced_buttons3_add":"tablecontrols,fullscreen",
				"plugins":"pdw,table,fullscreen,emotions",
				"language":"en",
				pdw_toggle_on: 1,
				pdw_toggle_toolbars: "2,3",
				"theme_advanced_disable" : "styleselect",
				"theme_advanced_fonts" : "Arial=arial,helvetica,sans-serif;Arvo=arvo,serif;Courier New=courier new,courier,monospace;Impact=impact, sans-serif;Nobile=nobile, sans-serif;PT Sans=pt sans, sans-serif;Verdana=verdana, sans-serif",
				"body_class": "user_content",
				gecko_spellcheck : true,
				"setup": function(ed) {
						ed.onBeforeSetContent.add(function(ed, cm) {
							tinyMCE.activeEditor.dom.addClass("tinymce","user_content");
							tinyMCE.activeEditor.dom.loadCSS('/assets/custom.css');
						});
				}
			});
			</script>
		eos
	end
end

app/views/static_pages/_first_time.html.erb
<div id="first-time" class="modal fade hide first-time">
	<img class="bg-pic" src="/assets/first-time.jpg" usemap="#map"/>
	<div class="dark-overlay"></div>
	<div class="dialog">
		<div class="title">
			Footbag Front
		</div>
		<div class="subtitle">
			Everything Freestyle Footbag
		</div>
		<%= link_to signup_path do %>
			<button class="btn btn-large btn-primary">
				JOIN NOW!
			</button>
		<% end %>
			<div id="close-btn">
				X
			</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		setTimeout(function() {
			$("#first-time").modal();
		}, 2500);
		$("#close-btn").click(function() {
			$('#first-time').modal('hide');
		});
	});

</script>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="light-box">
	<div class="content">
	<h1>About <%= site_name %></h1>
	<p>
	We're an online community site dedicated to the (awesome) sport of Freestyle Footbag.
	</p>
	<p>
	It was developed from scratch to provide Freestyle footbaggers a place on the internet to own and share information related to our sport. It will ALWAYS remain free for all players, and we'll do our best to make sure the information put in will never be lost.
	</p>
	<p>
	Please submit any bug report or feature request to Roy Klein	
	</p>

</div>
</div>

app/views/static_pages/admin.html.erb
<% if admin? %>
	<div class="light-box">
		<h3>Virtual Profiles</h3>
		<ul>
		<% @virtual_profiles.each do |u| %>
			<li><%= link_to u.name, u %> (<%= "#{u.email}" %>) | <%= link_to "edit", edit_user_path(u) %> | <%= link_to "delete", u, method: :delete, data: {confirm: "You sure?"} %></li>
		<% end %>
		</ul>
		<div class="spacer"></div>
		<% add_virtual_profile_func = 'NM.toggleVisibility("#profile_form");' %>
		<%= link_to_function "Add another...", add_virtual_profile_func %>
		<div id="profile_form" style="display:none;">
			<%= form_for(User.new) do |f| %>
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-input" %>

				<%= f.label :email %>
				<%= f.text_field :email, class: "form-input" %>

				<%= f.label :password  %>
				<%= f.password_field  :password, class: "form-input"  %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field  :password_confirmation, class: "form-input" %>
				<%= hidden_field_tag "challenge", "freestyle" %>
				<%= f.hidden_field :registered, value: false %>
				<%= hidden_field_tag :admin_created, true %>
				<div class="spacer"></div>
				<%= f.submit "Create virtual profile", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
	<div class="spacer"></div>
	<h3>Admins Hangout</h3>
	<div class="feed">
		<%= link_to feed_path(@feed.permalink, :atom) do %>
			<div>
				<%= image_tag("/assets/feed-icon-14x14.png", alt: "Admin feed", class: "video-feed-icon", width: 14, height: 14)%>
				Admin feed
			</div>
		<% end %>
		<%= render partial: 'shared/post_form', locals: {show_post: true, show_video: true} %>
		<% if @feed_items.any? %>
			<%= render partial: 'shared/feed_item', collection: @feed_items, comments_shown: false %>
		<% end %>
	</div>	
	<%= render 'shared/ajax_loading', collection: @feed_items, loadPath: feed_path(@feed.store_name) %>
<% end %>

app/views/static_pages/chat.html.erb
<html>
	<head>
		<title><%= full_title("Chat") %></title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= render 'layouts/shim' %>
	</head>
	<body class="popup dark">
		<header class="navbar navbar-fixed-top">
			<div class="navbar-inner headernav">
				<div class="container">
					<!-- Logo -->				
					<span class="header-logo">
						<a class="brand" href="/#">
							<p class="brand1"><%= site_name.split[0] %></p>
							<p class="brand2"><%= site_name.split[1] %>!</p>
						</a>
					</span>
				</div>
			</div>
		</header>
		<% if signed_in? %>
			<%= render 'shared/chat', popup: true %>
		
		<% else %>
			<div class="span6">
				<div class="light-box" style="margin-top:10px;">
					<h2>You must be signed in to chat</h2>
					<%= render '/shared/signin_form' %>
				</div>
		</div>
		<% end %>
	</body>	
</html>

app/views/static_pages/home.html.erb
<% provide(:title, t(:home)) %>
<% if @first_timer %>
	<%= render 'first_time' %>
<% end %>
<% if @feed_front_page %>
    <% if @video_of_day %>
        <div class="video_of_the_day" style="margin:10px;">
          <% if false %>
            <%= render 'shared/feed_item', :feed_item => @video_of_day, feed_item_counter: 0, show_comments: false %>
          <% end %>
          <div class="feed-item christmas">
            <div style="margin:10px">
                <%= render '/shared/video_item', :feed_item => @video_of_day%>
            </div>
          </div>
        </div>
    <% end %>
	<div style="position:relative">
		<div style="height:14px;position: absolute; top: 20px; right: 10px;">
			<%= link_to feed_path(@feed.permalink, :atom) do %>
				<span class="pull-right">
					<%= image_tag("/assets/feed-icon-14x14.png", alt: "front page feed", class: "video-feed-icon", width: 14, height: 14)%>
					<%= t(:front_page_feed) %>
				</span>
			<% end %>
		</div>
		<div class="front-page-feed feed">
			<%= render partial: 'shared/post_form', locals: {show_post: true, show_video: true, show_blog: true} %>

		</div>
		<% if @feed_items.any? %>
			<%= render 'shared/ajax_loading', collection: @feed_items, loadPath: '/', loadNow: true %>
		<% end %>
		<% if signed_in? %>
			<script>
				//NM.every(60000).refreshFeedItems();
			</script>
		<% end %>
	</div>
<% else %>
	<div class="light-box">
	<div class="content">
		<% unless @article.nil? %>
			<%= @article.content.html_safe %>
		<% end %>
	</div>
</div>
<% end %>

app/views/static_pages/unauthorized.html.erb
<div class="unauthorized">
	<h2>To view this content</h2>
	<%= image_tag("/assets/yodabag.png", alt: "haniabag yoda")%>
	<h2>logged in you must be!</h2>
</div>