config/routes.rb
NewModified::Application.routes.draw do
	root to: 'static_pages#home'

	match '/help', to: 'static_pages#help'

	match '/about', to: 'static_pages#about'

	match '/unauthorized', to: 'static_pages#unauthorized'

	match '/contact', to: 'static_pages#contact'

	match '/admin', to: 'static_pages#admin'

	match '/chat', to: 'static_pages#chat'

	match '/search', to: 'search#search_all'

	resources :users

	match '/user_videos', to: 'users#user_videos'
	match '/user_posts', to: 'users#user_posts'
	match '/user_articles', to: 'users#user_articles'
	match '/user_data', to: 'users#export'
	match '/who_online', to: 'users#who_online'
	match '/enable_chat', to: 'users#user_enable_chat'
	match '/timeline/:id', to: 'users#timeline'
	match '/sessions/:id', to: 'users#sessions_timeline'

	match '/signup', to: 'users#new'

	match '/clear_notifications', to: 'users#clear_notifications'

	match '/reset/:reset_code', to:'users#reset_password'

	match '/sorted_users', to:'users#sorted_index'

	resources :sessions, only: [:new, :create, :destroy]

	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete
	match '/signout', to: 'sessions#destroy'
	match '/forgotpassword', to: 'sessions#forgot_password'
	match '/resetpassword', to: 'sessions#reset_password'

	resources :feeds, only: [:index, :create, :update, :edit]

	match 'feeds/:permalink', controller: 'feeds', action: 'show', as: "feed"

	resources :achievements

	match 'new_achievement', controller: 'achievements', action: 'create'
	match 'update_achievement', controller: 'achievements', action: 'update'

	resources :training_sessions
	match 'new_training_session', controller: 'training_sessions', action: 'create'
	match 'update_training_session', controller: 'training_sessions', action: 'update'

	match 'training_drills/select', to: 'training_drills#select'
	match 'training_drills/init', to: 'training_drills#init'

	resources :training_drills

	resources :training_drill_results

	resources :posts

	resources :articles

	resources :videos do
		get 'search', on: :collection
		post 'touch'
	end

	match '/feedbacks', to: 'videos#feedback_index'

	match '/saveVideo', to: 'videos#import', via: :post

	resources :blog_posts

	resources :blogs

	match '/importblog', to:"blogs#import"
	match '/performimport', to:"blogs#perform_import"
	match '/perform_blogpost_import', to:"blogs#perform_blogpost_import"
	match '/initblog', to: "blogs#init_blog"
	match '/blogs/rename', to: "blogs#rename", via: :post

	resources :comments

	resources :messages, only: [:new, :create, :index, :show]

	match '/getmail', to: 'messages#get_latest'
	match '/markread', to: 'messages#mark_as_read'

	resources :conversations, only: [:show]

	resources :likes, only: [:new, :create, :destroy]

	match '/like', to: 'likes#create', via: :post
	match '/unlike', to: 'likes#destroy', via: :delete

	resources :notifications, only: [:index]
	match '/activities', to: 'notifications#index'
	match '/getnotifications', to: 'notifications#get_latest'

	resources :events
	resources :competitions, only: [:show, :update]

	match 'competition/reorder/:id', to: 'competitions#reorder', via: :put, as: "reorder"

	resources :results

	match 'static/:name', controller: 'pages', action: 'show', as: "page"

	match 'static/edit/:name', controller: 'pages', action: 'edit', as: "edit_page"

	match 'static/update/:name', controller: 'pages', action: 'update', via: :put

	resources :categories

	resources :video_categories

	resources :video_super_categories

	match 'video_tutorials/:permalink', controller: 'video_super_categories', action: 'show', as: "video_super_category"

	match '/stop_listening/:guid', to: 'listeners#remove_listener'

end

app/models/achievement.rb
# == Schema Information
#
# Table name: achievements
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  user_id          :integer
#  achievement_type :integer
#  date             :datetime
#  public           :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  video_id         :integer
#

class Achievement < ActiveRecord::Base
	acts_as_trashable
	attr_accessible :date, :name, :achievement_type, :user_id , :public, :video

	belongs_to :user
	has_many :notifications, as: :item, dependent: :destroy
	has_many :comments, as: :commentable, order: 'created_at ASC'
	has_many :listeners, as: :listened_to, dependent: :destroy
	has_many :likes, as: :liked_item, dependent: :destroy
	belongs_to :video
	accepts_nested_attributes_for :video

	validates :user_id, presence: true
	validates :name, presence: true
	validates :date, presence: true

	def get_type_name_for_feed
		case achievement_type
			when 0
				return "New Trick"
			when 1
				return "New Combo"
			when 2
				return "New Back to Back record"
			when 3
				return "Competition Result"
			when 4
				return "Completed a Challenge"
			when 5
				return "Important Event"
		end
	end
end

app/controllers/achievements_controller.rb
class AchievementsController  < AuthenticatedController
	include VideoHelper
	before_filter	:correct_user, only: [:destroy, :update]
	skip_before_filter :signed_in_user, only: [:index, :show]

	def show
		@achievement = Achievement.find(params[:id])
		if @achievement!=nil && !signed_in? && !@achievement.public
			signed_in_user
		end
	end

	def new
		new! { request.referer }
	end

	def create
		success = true
		begin
			params[:achievement][:date] = DateTime.strptime(params[:achievement][:date], "%m/%d/%Y")
		rescue
			success = false
			message = "Failed saving achievement: Invalid date."
		end
		if success
			@achievement = current_user.achievements.build(params[:achievement])
			@achievement.record_timestamps = false
			@achievement.created_at = DateTime.now
			@achievement.updated_at = @achievement.date
			success = attach_video(@achievement, params)
			if success
				success = @achievement.save
				if success
					message = "Achievement saved"
					if @achievement.updated_at>=Date.yesterday
						register_new_content(@achievement)
					end
				end
			end
			@achievement.record_timestamps = true
		end

		unless success
			message = flash[:error].blank? ? "Failed saving Achievement. Please make sure you filled all the required information." : flash[:error]
		end
		render json: {message: message, success:success}
	end

	def update
		success = true
		unless params[:achievement][:date].nil?
			begin
				params[:achievement][:date] = DateTime.strptime(params[:achievement][:date], "%m/%d/%Y")
			rescue
				success = false
				message = "Failed saving achievement: Invalid date."
			end
		end
		if success
			@achievement.update_attributes(params[:achievement])
			@achievement.record_timestamps = false
			@achievement.updated_at = @achievement.date
			unless params[:video].nil?
				attach_video(@achievement, params)
			end
			success = @achievement.save
			if success
				message = "Achievement updated"
			else
				message = flash[:error].blank? ? "Failed updating Achievement. Please make sure you filled all the required information." : flash[:error]
			end
			@achievement.record_timestamps = true
		end
		render json: {message: message, success:success}

	end

	def destroy
		@achievement.destroy
		flash[:success] = "Achievement deleted"
		redirect_to root_url
	end

	private


	def correct_user
		unless current_user.admin?
			@achievement = current_user.achievements.find_by_id(params[:id])
			redirect_to root_url if @achievement.nil?
		else
			@achievement = Achievement.find(params[:id])
		end
	end
end

app/views/shared/achievements/_edit_achievement_form.html.erb
<% is_new_entry = true if is_new_entry.nil?%>
<% submit_url ||="/new_achievement" %>
<% date = (achievement.date.nil? ? DateTime.now : achievement.date).strftime("%m/%d/%Y") %>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/flick/jquery-ui.min.css" rel="stylesheet" type="text/css">
<%= form_for(achievement, html: {id: "achievement_form"}) do |f| %>
	<%= f.select :achievement_type, options_for_select([["Hit new trick", 0], ["Hit new combo", 1], ["Back to Back record", 2], ["Competition Result", 3], ["Challenge met",4], ["Important Event", 5]]) %>
	<%= f.text_field(:name, :rows=>1, :cols=>2, :class=>"post-input", placeholder: "Achievement description")%>
	<%= f.text_field(:date, :rows=>1, :cols=>2, :class=>"post-input datepicker", placeholder: "Date Achieved (mm/dd/yyyy)", value: date) %>
	<p>Have video proof? (optional)</p>
<% end %>
<%= render '/shared/attachment_video_form', video: achievement.video, idsPrefix: "achievement"%>
<input type="submit" value="<%=is_new_entry ? "Save Achievement" : "Update Achievement"%>" class="btn btn-large btn-primary" name="commit" id="achievement_form_submit_btn">
<div class=".loading-indicator" id="achievement_form_loading_indicator" style="display:none"><img  src="/assets/ajax-loader.gif"/></div>
<script>
	var dataFunction = function() {
		var videoData = window.achievementprepareVideoData();
		var data = {
			utf8: "✓",
			authenticity_token: $("input[name='authenticity_token']").val(),
			<% unless achievement.id.nil?%> id: <%=achievement.id%> , <% end %>
			achievement: {
				achievement_type: $("#achievement_achievement_type").val(),
				name: $("#achievement_name").val(),
				date: $("#achievement_date").val()
			},
			video:videoData.video,
			players:videoData.players
		};
		return data;
	};
	NM.initForm("achievement_form", "<%=submit_url%>", dataFunction, {resetForm: <%=is_new_entry%>});
</script>

app/views/shared/achievements/_edit_menu.html.erb
<% if signed_in? && !achievement.nil? && (current_user.admin? || current_user==achievement.user) %>
	<li class="dropdown" style="float:left;">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			<i class="icon-cog"></i>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to "Edit Achievement", edit_achievement_path(achievement) %></li>
			<li><%= link_to t(:delete), achievement, method: :delete, data: {confirm: t(:delete_confirmation)} %></li>
		</ul>
	</li>
<% end %>